### PR TITLE
⛏ Clean ZelHash implementation ⛏ 

### PR DESCRIPTION
**Pull request by milesmanley**
Implementation of ZelHash

### CODE REVIEW

**Comment by egyptianbman** [comment]
Does this negate #3?

**Comment by milesmanley** [comment]
Yes

**Comment by egyptianbman** [comment]
@milesmanley it looks like one of the tests is failing:
```
➜ mocha


  equihashverify
Invalid solution: invalid collision length between StepRows
X[i]   = 006d480d49200247f30f7ac908fdcc07f31d0553bd0c24a30f7a150b1bbc
X[i+1] = 08b9270a630a00172c0999c30ec18003dda60cfce90a444801df3f03d3aa
    1) should return true for correct solution test

...

  5 passing (14ms)
  1 failing

  1) equihashverify
       should return true for correct solution test:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/test.js:11:16)
```

**Comment by egyptianbman** [comment]
I am also getting an error:
```
rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block decode failed"} 
```

When shares are submitted. I don't see anything in the node's debug.log.

**Comment by egyptianbman** [comment]
Found out that the rpc error was caused by my testnet node not pointing to the correct origin. The failing test is still an issue as it might indicate issues with other chains.

**Review by egyptianbman — APPROVED** [review]
I was able to get additional information from Lolliedieb. For background, here's the conversation:
image

**Pull request merged**
